package:
  name: sure
  version: !!str 1.2.9

source:
  fn: sure-1.2.9.tar.gz
  url: https://pypi.python.org/packages/source/s/sure/sure-1.2.9.tar.gz
  md5: 25d97e054e8c461fb0418a23143d4a15
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sure = sure:main
    #
    # Would create an entry point called sure that calls sure.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - mock
    - six

  run:
    - python
    - mock
    - six

test:
  # Python imports
  imports:
    - sure

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/gabrielfalcao/sure
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'utility belt for automated testing in python for python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
