package:
  name: petsc
  version: 3.4.5

source:
  fn: petsc-3.4.5.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-3.4.5.tar.gz

build:
  number: 1
  binary_relocation: true

requirements:
  build:
    - system
    - cmake
    - atlas
    - mpich2
    - mpiblacs
    - scalapack
    - metis
    - parmetis
    - mumps
    - python 2.7*
  run:
    - system
    - atlas
    - mpich2
    - mpiblacs
    - scalapack
    - metis
    - parmetis
    - mumps

about:
  home: http://www.mcs.anl.gov/petsc/
  license: BSD
