package:
  name: inrimage
  version: 4.6.5

source:
  fn: inrimage-4.6.5.tar.gz
  url: https://who.rocq.inria.fr/Dominique.Bereziat/ftp/inrimage/4.6.5/inrimage-4.6.5.tar.gz

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - system # [linux]
    - libxaw # [osx]
    - pkg-config # [osx]
    - libpng # [osx]
  run:
    - system # [linux]
    - libxaw # [osx]
    - libpng # [osx]

test:
  files:
    - a-1o-s.inr 
  commands:
    - par a-1o-s.inr

about:
  home: http://inrimage.gforge.inria.fr/
