package:
  name: buildbot-master
  version: 0.8.10

source:
  fn: v0.8.10.tar.gz
  url: https://github.com/buildbot/buildbot/archive/v0.8.10.tar.gz
  patches:
    # See: https://github.com/buildbot/buildbot/commit/dd6632af2d5925032f812ef3d5d6746c1281d727
    - fix_sqlalchemy_migrate_requirement.patch

build:
  number: 2
  binary_relocation: true

requirements:
  build:
    - pip
    - setuptools
    - python 2.7*
    - twisted >=11.0.0
    - jinja2 >=2.1
    - sqlalchemy-migrate ==0.6.1|==0.7.0|==0.7.1|==0.7.2
    - sqlalchemy >=0.6,<=0.7.10
    - dateutil ==1.5
  run:
    - python 2.7*
    - twisted >=11.0.0
    - jinja2 >=2.1
    - sqlalchemy-migrate ==0.6.1|==0.7.0|==0.7.1|==0.7.2
    - sqlalchemy >=0.6,<=0.7.10
    - dateutil ==1.5

about:
  home: http://buildbot.net/
  license: GPL2
