package:
  name: git
  version: 2.2.1

source:
  fn: git-2.2.1.tar.gz
  url: https://www.kernel.org/pub/software/scm/git/git-2.2.1.tar.gz

build:
  number: 0
  binary_relocation: false

requirements:
  build:
    - openssl
  run:
    - openssl

about:
  home: http://www.git-scm.com/
  license: GNU GPL v2
