package:
  name: git
  version: 2.2.1

source:
  fn: git-2.2.1.tar.gz
  url: https://www.kernel.org/pub/software/scm/git/git-2.2.1.tar.gz

build:
  number: 3
  binary_relocation: true
  detect_binary_files_with_prefix: true

requirements:
  build:
    - openssl
    - soften
  run:
    - openssl

about:
  home: http://www.git-scm.com/
  license: GNU GPL v2
