package:
  name: mpi4py
  version: 1.3.1

source:
  fn: mpi4py-1.3.1.tar.gz
  url: https://bitbucket.org/mpi4py/mpi4py/downloads/mpi4py-1.3.1.tar.gz

build:
  number: 2
  binary_relocation: true

requirements:
  build:
    - python 2.7*
    - mpich2 # [linux]
    - mpich2_cxx # [osx]
    - cython
  run:
    - python 2.7*
    - mpich2 # [linux]
    - mpich2_cxx # [osx]

about:
  home: https://bitbucket.org/mpi4py/mpi4py
  license: BSD
