package:
  name: mpip
  version: 3.4.1

source:
  fn: mpiP-3.4.1.tar.gz
  url: http://downloads.sourceforge.net/project/mpip/mpiP/mpiP-3.4.1/mpiP-3.4.1.tar.gz

build:
  number: 0
  binary_relocation: true
  string: mpich_0

requirements:
  build:
    - mpich # https://binstar.org/mpi4py/mpich
    - libunwind
    - libelf
    - libdwarf
  run:
    - mpich # https://binstar.org/mpi4py/mpich
    - libunwind
    - libelf
    - libdwarf

about:
  home: http://mpip.sourceforge.net/ 
  license: BSD
