package:
  name: itk-heimdali
  version: 4.7.0

source:
  git_url: https://github.com/dfroger/ITK
  git_tag: v4.7.0heimdali.0

build:
  number: 1
  binary_relocation: true

requirements:
  build:
    - cmake
    - system # [linux]
    - zlib
    - libtiff
    - libpng
    - jpeg
    - hdf5_cxx
  run:
    - system # [linux]
    - zlib
    - libtiff
    - libpng
    - jpeg
    - hdf5_cxx

test:
  files:
    - CMakeLists.txt
    - CreateVector.cxx
  requires:
    - cmake
  commands:
    - mkdir build
    - cd build
    - hash -r
    - cmake -DCMAKE_PREFIX_PATH=$PREFIX ..
    - make

about:
  home: http://www.itk.org/
  license: Apache 2.0
