package:
  name: python-magic
  version: 0.4.11

source:
  fn: python-magic-0.4.11.tar.gz
  url: https://pypi.python.org/packages/bb/03/1246519939004c60fc34c7bed9c0ab0e7d1b972b9278e5394bed942446a3/python-magic-0.4.11.tar.gz
  md5: 3c1cdcb8fc0ec4ea5a0cf2230c929c76

build:
  number: 0

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - magic 

about:
  home: https://github.com/ahupp/python-magic
  license: MIT
