package:
  name: mpich
  version: 3.1.3

source:
  fn: mpich-3.1.3.tar.gz
  url: http://www.mpich.org/static/downloads/3.1.3/mpich-3.1.3.tar.gz

build:
  number: 2
  binary_relocation: true

requirements:
  build:
    - gcc
  run:
    - gcc

about:
  home: http://www.mpich.org/
  license: BSD
