package:
  name: hieroglyph
  version: 0.7.1.20151006

source:
  git_url: https://github.com/nyergler/hieroglyph

build:
  number: 0

requirements:
  build:
    - python
    - pip
    - sphinx
  run:
    - python
    - sphinx

test:
  commands:
    - hieroglyph

about:
  home: https://github.com/nyergler/hieroglyph
  license: BSD
