package:
  name: libdwarf
  version: 20150310

source:
  fn: libdwarf-20150310.tar.gz
  url: http://www.prevanders.net/libdwarf-20150310.tar.gz

requirements:
  build:
    - libelf
  run:
    - libelf

build:
  number: 0
  binary_relocation: true

about:
  home: http://www.prevanders.net/dwarf.html
  license: GPL
