package:
  name: parmetis
  version: 4.0.3

source:
  fn: parmetis-4.0.3.tar.gz
  url: http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/parmetis-4.0.3.tar.gz

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - cmake
    - mpich2
  run:
    - mpich2

about:
  home: http://glaros.dtc.umn.edu/gkhome/metis/parmetis/overview
  license: University of Minnesota
