package:
  name: mumps
  version: 4.10.0

source:
  fn: MUMPS_4.10.0.tar.gz
  url: http://mumps.enseeiht.fr/MUMPS_4.10.0.tar.gz

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - system
    - atlas
    - mpich2
    - mpiblacs
    - scalapack
    - parmetis
  run:
    - system
    - atlas
    - mpich2
    - mpiblacs
    - scalapack
    - parmetis

about:
  home: http://mumps.enseeiht.fr/
  license: Public domain
