package:
  name: gpgme
  version: 1.5.5

source:
  fn: gpgme-1.5.5.tar.bz2
  url: https://www.gnupg.org/ftp/gcrypt/gpgme/gpgme-1.5.5.tar.bz2

build:
  number: 1

requirements:
  build:
    - libgpg-error
    - libassuan
  run:
    - libgpg-error
    - libassuan

about:
  home: https://www.gnupg.org/%28it%29/related_software/gpgme/index.html
  license: GPL
  summary: GnuPG Made Easy (GPGME) is a library designed to make access to GnuPG easier for applications.
