package:
  name: vxl 
  version: 1.17.0

source:
  fn: vxl-1.17.0
  url: http://sourceforge.net/projects/vxl/files/vxl/1.17/vxl-1.17.0.tar.gz

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - cmake
    - bzip2
    - zlib
  run:
    - bzip2
    - zlib

about:
  home: http://vxl.sourceforge.net/
  license: BSD-3-Clause
