package:
  name: urwid
  version: 1.3.0

source:
  fn: urwid-1.3.0.tar.gz
  url: https://pypi.python.org/packages/source/u/urwid/urwid-1.3.0.tar.gz

build:
  number: 0

requirements:
  build:
    - pip
    - python
  run:
    - python

test:
  imports:
    - urwid

about:
  home: http://urwid.org
  license: LGPL
