package:
  name: alot
  version: 2016.03.30

source:
  git_url: https://github.com/pazz/alot

build:
  number: 0

requirements:
  build:
    - pip
    - python
    - libmagic
    - configobj
    - twisted
    - notmuch
    - urwid
    - urwidtrees
    - pygpgme 
  run:
    - python
    - libmagic
    - configobj
    - twisted
    - notmuch
    - urwid
    - urwidtrees
    - pygpgme 

test:
  commands:
    - alot --help

about:
  home: https://github.com/pazz/alot
  license: GPL3
  summary:  commandline MUA using notmuch and urwid
