package:
  name: mpich_cxx
  version: 3.1.4

source:
  fn: mpich-3.1.4.tar.gz
  url: http://www.mpich.org/static/downloads/3.1.4/mpich-3.1.4.tar.gz

build:
  number: 0
  binary_relocation: true

test:
  commands:
    - mpirun --help

about:
  home: http://www.mpich.org/
  license: BSD
