package:
  name: mpich_cxx
  version: 1.4.1p1

source:
  fn: mpich2-1.4.1p1.tar.gz 
  url: http://www.mpich.org/static/downloads/1.4.1p1/mpich2-1.4.1p1.tar.gz 

build:
  number: 0
  binary_relocation: true

about:
  home: http://www.mpich.org/
  license: BSD
