package:
  name: libmagic
  version: 5.18

source:
  fn: 5.18.tar.gz
  url: https://github.com/threatstack/libmagic/archive/5.18.tar.gz

build:
  number: 1

requirements:
  build:
    - pip
    - python
  run:
    - python

test:
  imports:
    - magic

about:
  home: https://github.com/threatstack/libmagic
  license: BSD
  summary: Magic number recognition library.
