package:
  name: pyvtk
  version: 0.4.85

source:
  fn: PyVTK-0.4.85.tar.gz
  url: https://pypi.python.org/packages/source/P/PyVTK/PyVTK-0.4.85.tar.gz

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - pip

about:
  home: https://code.google.com/p/pyvtk/
  license:  New BSD License
