package:
  name: libmagic
  version: 5.18

source:
  fn: 5.18.tar.gz
  url: https://github.com/threatstack/libmagic/archive/5.18.tar.gz

build:
  number: 0

requirements:
  build:
  run:

about:
  home: https://github.com/threatstack/libmagic
  license: BSD
  summary: Magic number recognition library.
