package:
  name: termcolor
  version: 1.1.0

source:
  fn: termcolor-1.1.0.tar.gz
  url: https://pypi.python.org/packages/source/t/termcolor/termcolor-1.1.0.tar.gz

build:
  number: 0

requirements:
  build:
    - pip
    - python
  run:
    - python

about:
  home: https://pypi.python.org/pypi/termcolor
  license: MIT
