package:
  name: notmuch
  version: 0.20.2

source:
  fn: notmuch-0.20.2.tar.gz
  url: http://notmuchmail.org/releases/notmuch-0.20.2.tar.gz

build:
  number: 0

requirements:
  build:
    - xapian
    - gmime # TODO
    - talloc # TODO
  run:
    - xapian
    - gmime
    - talloc

about:
  home: http://notmuchmail.org
  license: GPLv3
  summary: Fast, global-search and tag-based email system to use within your text editor or in a terminal
