package:
  name: igprof
  version: 5.9.11

source:
  fn: v5.9.11.tar.gz 
  url: https://github.com/ktf/igprof/archive/v5.9.11.tar.gz 

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - cmake
    - libatomic_ops
    - libunwind
  run:
    - libatomic_ops
    - libunwind

about:
  home: http://igprof.org/
  license: GPL 2
