package:
  name: superlu_dist
  version: 3.3

source:
  fn: superlu_dist_3.3.tar.gz
  url: http://crd-legacy.lbl.gov/~xiaoye/SuperLU/superlu_dist_3.3.tar.gz

build:
  number: 1
  binary_relocation: true

requirements:
  build:
    - atlas
    - mpich2
    - metis
    - parmetis
  run:
    - atlas
    - mpich2
    - metis
    - parmetis

about:
  home: http://crd-legacy.lbl.gov/~xiaoye/SuperLU/
  license: University of California
