package:
  name: runipy
  version: 0.1.3.dfroger.0

source:
  git_url: https://github.com/dfroger/runipy
  git_tag: 0.1.3.dfroger.0

build:
  number: 0

requirements:
  build:
    - python
    - jinja2 >=2.7.2
    - pygments >=1.6
    - ipython >=2.3.1
    - pyzmq >=14.1.0
    - jsonschema
  run:
    - python
    - jinja2 >=2.7.2
    - pygments >=1.6
    - ipython >=2.3.1
    - pyzmq >=14.1.0
    - jsonschema

test:
  commands:
    - runipy --help

about:
  home: https://github.com/paulgb/runipy
  license: BSD
