package:
  name: ccache
  version: 3.2.2

source:
  fn: ccache-3.2.2.tar.bz2
  url: http://samba.org/ftp/ccache/ccache-3.2.2.tar.bz2
  patches: 
    - configure.patch

build:
  number: 3

requirements:
  build:
    - zlib
  run:
    - zlib

about:
  home: https://ccache.samba.org/
  license: GNU General Public License version 3 or later
