package:
  name: libiconv
  version: 1.14

source:
  fn: libiconv-1.14.tar.gz
  url: http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.14.tar.gz

build:
  number: 0

requirements:
  build:
  run:

about:
  home: http://www.gnu.org/software/libiconv
  license: GPL
  summary: libiconv converts from one character encoding to another through Unicode conversion.
