package:
  name: afew
  version: 2016.02.29

source:
  git_url: https://github.com/teythoon/afew

build:
  number: 0

requirements:
  build:
    - pip
    - python
    - dbacl 
    - notmuch 
    - chardet
    - subprocess32
  run:
    - python
    - dbacl 
    - notmuch 
    - chardet
    - subprocess32

test:
  commands:
    - afew --help

about:
  home: https://github.com/teythoon/afew
  license: ISC
  summary:  afew is an initial tagging script for notmuch mail
